In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)

In [2]:
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
pd.options.display.max_columns = 20
np.random.seed(12345)
import matplotlib.pyplot as plt
import matplotlib
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

#### (1) Load the data from Excel into DataFrames

In [3]:
groups={
    "P222": "G1",
    "P216": "G1",
    "P164": "G1",
    "P193": "G1",
    "P174": "G1",
    "P215": "G1",
    "P200": "G1",
    "P163": "G1",
    "P168": "G1",
    "P197": "G1",
    "P217": "G1",
    "P160": "G1",
    "P177": "G1",
    "P151": "G1",
    "P171": "G2",
    "P239": "G2",
    "P115": "G2",
    "P236": "G2",
    "P70":  "G2",
    "P99":  "G2",
    "P234": "G2",
    "P248": "G2",
    "P228": "G2",
    "P213": "G2",
    "P240": "G2",
    "P117": "G2",
    "P107": "G2",
    "P244": "G2",
    "P132": "G2",
    "P241": "G2"
}

In [4]:
def my_file_reader(fn, idx):
    pd_fl = pd.read_csv(fn, sep="\t", index_col=idx)
    cnt = pd_fl.shape[0] - ((pd_fl ==0 ).sum())
    return cnt

### The actual numbers of taxonomy in each sample

In [5]:
class_cnt = my_file_reader('Unigenes.absolute.s.xls', "Taxonomy")
class_cnt

P222    3467
P216    1629
P164    2435
P193    2905
P174    1318
        ...
P117    2131
P107    3095
P244    2413
P132    2426
P241    1205
Length: 30, dtype: int64

### The mean abundance of family, genus, species, etc., in each group

In [6]:
tax = pd.read_csv('Unigenes.absolute.s.xls', sep="\t", index_col="Taxonomy")

In [7]:
tax

,P222,P216,P164,P193,P174,P215,P200,P163,P168,P197,...,P234,P248,P228,P213,P240,P117,P107,P244,P132,P241
Taxonomy,,,,,,,,,,,,,,,,,,,,,
Others,187412,54131,98648,119080,40637,81627,82207,219942,117229,64456,...,100144,60856,80819,171430,131272,126170,157663,143425,159902,49094
g__Treponema;s__Treponema denticola,4800,951,2870,5798,2431,6714,3111,8251,1484,2161,...,1767,2018,66,3475,3113,522,2627,247,335,477
g__Fusobacterium;s__Fusobacterium nucleatum,6486,1465,5008,4467,2770,3437,4857,7773,5198,2392,...,3812,2937,2759,6525,5244,3460,5556,6383,5793,3837
g__Fretibacterium;s__Fretibacterium sp. OH1220_COT-178,5608,2257,5518,4720,2061,4786,2970,7473,3730,1055,...,2196,1652,97,3837,4507,1788,7115,3634,1607,1514
g__Fretibacterium;s__Fretibacterium fastidiosum,5937,1333,5052,4121,1019,3796,2116,6206,2253,433,...,1674,985,91,3044,3644,413,6168,3302,1314,330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
g__Unclassified;s__Streptococcus phage Javan318,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
g__Unclassified;s__Streptococcus phage MissE2,0,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
g__Unclassified;s__Streptococcus phage OlisA2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
g__Unclassified;s__TM7 phage DolZOral124_53_65,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
g__Unclassified;s__Tenacibaculum phage JQ,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0

In [8]:
tax2 = tax.loc[['g__Porphyromonas;s__Porphyromonas gingivalis','g__Streptococcus;s__Streptococcus cristatus'],].T
tax2

Taxonomy,g__Porphyromonas;s__Porphyromonas gingivalis,g__Streptococcus;s__Streptococcus cristatus
P222,2575,1040
P216,1841,73
P164,2314,174
P193,2290,196
P174,1994,70
...,...,...
P117,234,1105
P107,764,937
P244,292,821
P132,338,1152
P241,153,74

In [9]:
tax2.describe()

Taxonomy,g__Porphyromonas;s__Porphyromonas gingivalis,g__Streptococcus;s__Streptococcus cristatus
count,30.000000,30.000000
mean,1247.500000,660.566667
std,941.256634,414.950989
min,125.000000,70.000000
25%,304.250000,224.000000
50%,821.500000,747.500000
75%,2215.500000,1031.000000
max,2575.000000,1373.000000

In [10]:
tax2['tax_cnt'] = class_cnt
tax2

Taxonomy,g__Porphyromonas;s__Porphyromonas gingivalis,g__Streptococcus;s__Streptococcus cristatus,tax_cnt
P222,2575,1040,3467
P216,1841,73,1629
P164,2314,174,2435
P193,2290,196,2905
P174,1994,70,1318
...,...,...,...
P117,234,1105,2131
P107,764,937,3095
P244,292,821,2413
P132,338,1152,2426
P241,153,74,1205

In [11]:
tax2.describe()

Taxonomy,g__Porphyromonas;s__Porphyromonas gingivalis,g__Streptococcus;s__Streptococcus cristatus,tax_cnt
count,30.000000,30.000000,30.000000
mean,1247.500000,660.566667,2538.533333
std,941.256634,414.950989,736.152708
min,125.000000,70.000000,1205.000000
25%,304.250000,224.000000,2176.500000
50%,821.500000,747.500000,2464.000000
75%,2215.500000,1031.000000,2913.250000
max,2575.000000,1373.000000,4434.000000

In [22]:
tax2.to_excel("Tax-abundance.xlsx")